### ISSUE TITLE
Store and use quick-hashed values for reverse lookups

### ISSUE THREAD

**Issue by rnewman** [mozilla/datomish#12]
A common pattern is to refer to records by some unique property:

```
[:find ?title :where [
  [[:page/url ?] :page/title ?title]
]]
; Binding: "http://foo.com/"
```

That involves matching string values of `:page/url` to find a page, then fanning back out to title, or matching all titles and pages and narrowing by URL.

Rather than doing string matching directly, it's often more efficient to store a known hash of a value, and query with a pattern like:

```["… WHERE datoms.vh = ? AND datoms.v = ?" (quick-hash val) val]```

We should optionally store these in the DB:

```
vh INTEGER       // Can be null
```

With a partial index:

```
CREATE INDEX idx_vh ON datoms (vh, v, p) WHERE vh IS NOT NULL;
```

and then add flags to opt in or out on a per-attribute level. We might choose to do this automatically for string-valued unique attributes like `:page/url`.

**Comment by ncalexan** [comment]
This is an interesting proposal.  I like the last part: "automatic[ally] for string-valued unique attributes".

**Comment by rnewman** [comment]
Places just made a similar change, and IIRC achieved index size reductions
(no URL strings in indices) and probably some speed ups.
