### ISSUE TITLE
Clojurescript implementation link

### ISSUE THREAD

**Issue by cldwalker** [mozilla/datomish#140]
Hi,
  We in the clojurescript and datomic communities are excited with the work you're doing here. It would be great to link to the clojurescript version in the readme e.g. "was written in ClojureScript" to quickly read up on what was attempted. I'm happy to open a PR for it if you'd like. Seems the last full clojurescript version was https://github.com/mozilla/datomish/tree/9cc26616a9b6a702db1a5a95933af5b5df9919e4

Cheers

**Comment by rnewman** [comment]
I added a back-pointer to `master` (which is still the ClojureScript version) in https://github.com/mozilla/datomish/commit/fa3c99f550e5d9b06f56c7a76168ff48284cbc83. Thanks for the note!

**Comment by cldwalker** [comment]
Thanks!
