### ISSUE TITLE
Stable release

### ISSUE THREAD

**Issue by chrmod** [mozilla/datomish#145]
v0.3.1 does not work in node or firefox addon - that error seems to be the same as for https://github.com/mozilla/datomish/issues/122

with master there also seems to be some issues.

Which version should be used for Firefox Addon development?

**Comment by chrmod** [comment]
will report exact error from Firefox Tomorrow morning, need to get logs from my office machine.

**Comment by chrmod** [comment]
there is no tag v0.3.5 on github, which commit was used to build that version on clojars?

**Comment by rnewman** [comment]
https://github.com/mozilla/datomish/commit/7cf67474a8a774b37fd734a961f47a92a7ca38c6

**Comment by chrmod** [comment]
the error I'm getting on transact on newly created database:
```
NS_ERROR_UNEXPECTED: Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [mozIStorageAsyncStatement.bindByIndex]  Sqlite.jsm:700
```

**Comment by rnewman** [comment]
Filed #146.
