### ISSUE TITLE
Queries hang if they fail

### ISSUE THREAD

**Issue by rnewman** [mozilla/datomish#40]
`<?all-rows` only fills and closes its channel if it gets results. Otherwise, the channel blocks forever. Oops.

**Comment by rnewman** [comment]
More accurately: when `-each` rejects its promise, `<?all-rows` doesn't close its channel.

**Comment by rnewman** [comment]
Hooray for untyped languages. `(put! result c)` instead of the correct `(put! c result)`.

**Comment by ncalexan** [comment]
lgtm.  I assume this in your branch somewhere and we'll merge our work sometime soon.

**Comment by rnewman** [comment]
Yeah, it's 8b45f0f — GitHub handily shows it ⬆️.

**Comment by rnewman** [comment]
Fixed in b2a1af30ed6f13ca72012a317b81a5a8127ecf3f.
