### ISSUE TITLE
Don't touch SQL store when allocating entids

### ISSUE THREAD

**Issue by ncalexan** [mozilla/datomish#47]
Right now, we query and insert entids into the SQL store each time we allocate a tempid.  This can be avoided by keeping temporary data in the `TxReport` and updating the SQL store just once per transaction.

**Comment by rnewman** [comment]
Will this behave correctly if two transacts are built interleaved?

**Comment by ncalexan** [comment]
> Will this behave correctly if two transacts are built interleaved?

Right now, yes -- because `<transact!` opens an exclusive transaction immediately.  If we cared to eke out the last inch of interleaving performance, we could try to delay the transaction opening, but I think that inch is very small indeed.

**Comment by ncalexan** [comment]
https://github.com/ncalexan/datomish/commit/e48f58f5f4a366a6d640321b1b953a5e3b94cbd2
