### ISSUE TITLE
Don't use rowids as foreign key into fulltext values table

### ISSUE THREAD

**Issue by ncalexan** [mozilla/datomish#67]
Per http://www.sqlabs.com/blog/2010/12/sqlite-and-unique-rowid-something-you-really-need-to-know/ and others, `VACUUM` can re-assign rowids.  At this time, we don't ever delete fulltext values, so this is a theoretical concern; but we should fix it, possibly by adding an `INTEGER PRIMARY KEY AUTOINCREMENT` to the fulltext values table.

**Comment by rnewman** [comment]
“The rowid of an FTS table behaves in the same way as the rowid column of an ordinary SQLite table, except that the values stored in the rowid column of an FTS table remain unchanged if the database is rebuilt using the VACUUM command. For FTS tables, "docid" is allowed as an alias along with the usual "rowid", "oid" and "_oid_" identifiers.”
