### ISSUE TITLE
Change license to Apache

### ISSUE THREAD

**Issue by ncalexan** [mozilla/datomish#74]
Right now, [Datomish is MPL](https://github.com/mozilla/datomish/blob/0789219551e460624e4825ec883fc940322deccd/LICENSE).  [Tofino is Apache](https://github.com/mozilla/tofino/blob/6fd8111444008e3ad986daf0a52940497c756045/LICENSE).

I discussed with @joewalker and we would like to make Datomish Apache, or dual license it.

**Comment by rnewman** [comment]
👍
