### ISSUE TITLE
Make `<transact!` run in a critical section

### ISSUE THREAD

**Issue by ncalexan** [mozilla/datomish#80]
This is https://github.com/mozilla/tofino/issues/1321.  What's happening is that we're not "throttling" `<transact!` to be in a critical section.

**Comment by rnewman** [comment]
This is the fanciest mutex I ever did see.

**Comment by ncalexan** [comment]
I know.  Happy to see a less fancy one!  If we had an unbounded core.async
queue, we'd be golden.  The complexity is all about waking in order on the
JS side of the house.

**Comment by ncalexan** [comment]
https://github.com/mozilla/datomish/commit/ed545d4a11312e6e3a243d127c49b6c01855a8fb
